language: node_js
dist: trusty
before_script:
  - npm list -g firebase-tools --depth=0 || npm install -g firebase-tools
script:
  - npm install
  - npm run build
after_success:
- "./deploy.sh"
cache:
  directories:
    - '$(npm config get prefix)/bin/firebase-tools'
    - node_modules
notifications:
  email: false
  webhooks: https://travis.webhooks.m4m.io
