# Dependencies
markdown:           kramdown
kramdown:
  extensions: ["tables"]

highlighter:         rouge

# Permalinks
permalink:           /:year/:month/:day/:title.html

# Setup
title:               Geek Bites
tagline:             Blog by M4M developers
url:                 https://move4mobile.github.io

paginate:            1

baseurl:             ""
analytics_id:        UA-31584143-2

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Michael Schilling
  url:               https://twitter.com/mschilling
  email:             mschilling@move4mobile.com

# Custom vars
version:             1.0.0

github:
  repo:              github.com/move4mobile/move4mobile.github.io

# This is the list of pages to include in the header of the website.
pages_list:
#  About: '/about/'
  Archief: '/archive/'

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
# Gems
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist
